export const NEW_GAME = 'NEW_GAME';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const CLOCK_UPDATE = 'CLOCK_UPDATE';
export const USER_FIND_SOMETHING = 'USER_FIND_SOMETHING';
export const TOGGLE_WINING_STATUS = 'TOGGLE_WINING_STATUS';